
import first from '../../../../assets/img/first.jpg'
import lake from '../../../../assets/img/lake.jpg'
import bridge from '../../../../assets/img/bridge.jpg'
import scate from '../../../../assets/img/scate.jpg'
import bmx from '../../../../assets/img/bmx.jpg'
import baggi from '../../../../assets/img/baggi.jpg'

const articles = [
{
    id:1,
    img: first,
    imageLink:"/",
    iconCategories: <i className="fas fa-map-marker-alt"></i>,
    categoriesLink:"/",
    categories:" Travel",
    iconDate:<i className="far fa-clock"></i>,
    date:" April 27, 2021",
    title:"In hendrerit nulla quam nunc",
    titleLink:"/",
    description:"Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.",
    iconLike:<i className="far fa-heart"></i>,
    likeLink:"/",
    like:"12",
    iconRead:<i className="far fa-newspaper"></i>,
    readLink:"/",
    read:"Read more",
},

{
    id:2,
    img: lake,
    imageLink:"/",
    iconCategories: <i className="fas fa-map-marker-alt"></i>,
    categoriesLink:"/",
    categories:" Travel",
    iconDate:<i className="far fa-clock"></i>,
    date:" April 27, 2021",
    title:"In hendrerit nulla quam nunc",
    titleLink:"/",
    description:"Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.",
    iconLike:<i className="far fa-heart"></i>,
    likeLink:"/",
    like:"16",
    iconRead:<i className="far fa-newspaper"></i>,
    readLink:"/",
    read:"Read more",
},

{
    id:3,
    img: bridge,
    imageLink:"/",
    iconCategories: <i className="fas fa-map-marker-alt"></i>,
    categoriesLink:"/",
    categories:" Travel",
    iconDate:<i className="far fa-clock"></i>,
    date:" April 27, 2021",
    title:"In hendrerit nulla quam nunc",
    titleLink:"/",
    description:"Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.",
    iconLike:<i className="far fa-heart"></i>,
    likeLink:"/",
    like:"11",
    iconRead:<i className="far fa-newspaper"></i>,
    readLink:"/",
    read:"Read more",
},

{
    id:4,
    img: scate,
    imageLink:"/",
    iconCategories: <i className="fas fa-map-marker-alt"></i>,
    categoriesLink:"/",
    categories:" Extreme",
    iconDate:<i className="far fa-clock"></i>,
    date:" April 27, 2021",
    title:"In hendrerit nulla quam nunc",
    titleLink:"/",
    description:"Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.",
    iconLike:<i className="far fa-heart"></i>,
    likeLink:"/",
    like:"12",
    iconRead:<i className="far fa-newspaper"></i>,
    readLink:"/",
    read:"Read more",
},

{
    id:5,
    img: bmx,
    imageLink:"/",
    iconCategories: <i className="fas fa-map-marker-alt"></i>,
    categoriesLink:"/",
    categories:" Extreme",
    iconDate:<i className="far fa-clock"></i>,
    date:" April 27, 2021",
    title:"In hendrerit nulla quam nunc",
    titleLink:"/",
    description:"Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.",
    iconLike:<i className="far fa-heart"></i>,
    likeLink:"/",
    like:"12",
    iconRead:<i className="far fa-newspaper"></i>,
    readLink:"/",
    read:"Read more",
},

{
    id:6,
    img: baggi,
    imageLink:"/",
    iconCategories: <i className="fas fa-map-marker-alt"></i>,
    categoriesLink:"/",
    categories:" Extreme",
    iconDate:<i className="far fa-clock"></i>,
    date:" April 27, 2021",
    title:"In hendrerit nulla quam nunc",
    titleLink:"/",
    description:"Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi.",
    iconLike:<i className="far fa-heart"></i>,
    likeLink:"/",
    like:"12",
    iconRead:<i className="far fa-newspaper"></i>,
    readLink:"/",
    read:"Read more",

}
]

export default articles